targets:
  dev:
    mode: development
    default: true
    workspace:
      host : https://dbc-a73655c8-8153.cloud.databricks.com
      root_path: /Workspace/Users/${workspace.current_user.userName}/.bundles/${bundle.name}/${bundle.target}
    variables:
      environment: dev
      catalog: dev
      schema_bronze: bronze
      schema_silver: silver
      schema_gold: gold
      warehouse_id: afb90bfccc65e2e0